### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by mberz** [pyfar/haiopy#7]
Planned features

**v0.1.0**

- [x] Buffers for block-wise iteration of pyfar.Signal #5 

**Audio Devices**
- [ ] InputAudioDevice
- [ ] OutputAudioDevice #9 
- [ ] PlaybackRecord oder so

**User Level I/O**
- [ ] AudioRecorder
- [ ] AudioPlayer
- [ ] PlaybackRecord

User level implementations of
- [ ] Setting gain

Docs
- [ ] Class and function documentation 
- [ ] Outline of concepts
- [ ] Example notebooks

**v0.2.0**

- [ ] Calibration of DeviceChains
